#
# Copyright 2015 Midokura SARL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
- name: Install MySQL packages
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python
  when: ansible_distribution_major_version == '7'

- name: Install MySQL packages
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql
    - MySQL-python
  when: ansible_distribution_major_version == '6'

- name: Set facts
  set_fact: mysql_service=mariadb
  when: ansible_distribution_major_version == '7'

- name: Set facts
  set_fact: mysql_service=mysqld
  when: ansible_distribution_major_version == '6'

- name: Ensure MariaDB service is started and enabled
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: Set mysql password
  shell: "mysqladmin -u root password {{ admin_password }}"
  ignore_errors: yes

- name: Add openstack mysql config
  copy: src=openstack.cnf dest=/etc/my.cnf.d/openstack.cnf
  notify:
    - Restart mysql
  when: ansible_distribution_major_version == '7'

- name: Add mysql config
  copy: src=my.cnf dest=/etc/my.cnf
  notify:
    - Restart mysql
  when: ansible_distribution_major_version == '6'

- name: Set MySQL max connections
  ini_file: dest=/etc/my.cnf section=mysqld option=max_connections value='1024'
  notify:
    - Restart mysql

- name: Set MySQL listen address
  ini_file: dest=/etc/my.cnf section=mysqld option=bind-address value={{ mysql_listen_ip }}
  notify:
    - Restart mysql
